version: "3.5"
services:
  test_pg:
    image: "postgres:latest"
    container_name: test_pg
    ports:
      - "18080:5432"
    volumes:
      - ./gen:/home/generate
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres

  redis:
    image: redis:latest
    ports:
      - "6379:6379"